apiVersion: v1
kind: Service
metadata:
  name: minecraft-a-service
spec:
  selector:
    app: minecraft-server-a  # Use the label that matches your Minecraft server pods
  ports:
    - protocol: TCP
      port: 25565            # The port used by Minecraft
      targetPort: 25565
  type: NodePort