apiVersion: v1
kind: Service
metadata:
  name: minecraft-c-service
spec:
  selector:
    app: minecraft-server-c  # Use the label that matches your Minecraft Server C pods
  ports:
    - protocol: TCP
      port: 25565            # The port used by Minecraft
      targetPort: 25565
  type: NodePort